### ISSUE TITLE
Problem with centering image

### ISSUE THREAD

**Issue by darkdaisy** [anhkind/center_image_tag#1]
Hello world, 

I'm a beginner and am desperately trying to center an image on my blog, in the  section, I would like the <img alt> to be centered, right now it appears on the left of the screen.
Thank you so much for your help !

Here's the code for the logo.

```
<div id="logo" class="ht-animated-10 ht-fadeInLeft">
    <a title="<?php bloginfo( 'name' ); ?>" href="<?php echo esc_url( home_url() ); ?>">
        <img alt="<?php bloginfo( 'name' ); ?>" src="<?php echo esc_url( ht_theme_logo() ); ?>" />
    </a>
</div>
<!-- /#logo -->
```

**Comment by anhkind** [comment]
Seems that your code is in PHP,  you can get to following pages for the CSS references:
- http://jonathannicol.com/blog/2014/06/16/centre-crop-thumbnails-with-css/
- https://github.com/anselmh/object-fit
